version: "3.9"

services:
  kong:
    image: kong/kong-gateway:3.4
    ports:
      - 80:8000
      - 443:8443
      - 8001:8001
      - 8444:8444
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=password
      - POSTGRES_DB=kong
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    env_file:
      - .env
    networks:
      - local_network

  kong-migrations:
    profiles:
      - initial
    build:
      context: .
      dockerfile: ./docker/kong-migrations/Dockerfile
    entrypoint: /usr/local/bin/entrypoint.sh
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=password
      - POSTGRES_DB=kong
    networks:
      - local_network

  kong-manager:
    build:
      context: .
      dockerfile: ./docker/kong-manager/Dockerfile
    ports:
      - 8002:8002
    volumes:
      - ./docker/kong-manager/server_blocks/default.conf:/opt/bitnami/openresty/nginx/conf/server_blocks/default.conf

  postgres:
    image: postgres:13.12-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=password
    networks:
      - local_network

volumes:
  postgres_volume:
    driver: local

networks:
  local_network:
    driver: bridge
