version: "3.9"

services:
  kong:
    image: kong:3.4
    build:
      context: .
      dockerfile: ./docker/kong/Dockerfile
    command: kong docker-start
    restart: always
    ports:
      - 80:8080
      - 443:8443
      - 8001:8001
      - 8002:8002
      - 8444:8444
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=mFXxRW37CGET
      - KONG_PROXY_LISTEN=0.0.0.0:8080, 0.0.0.0:8443 ssl
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
      - ./docker/kong/templates/nginx_kong.lua:/usr/local/share/lua/5.1/kong/templates/nginx_kong.lua
    env_file:
      - .env
    networks:
      - local_network

  postgres:
    image: postgres:16.2-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - local_network

volumes:
  postgres_volume:
    driver: local

networks:
  local_network:
    driver: bridge